version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: syncin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: syncin_db
      MYSQL_USER: jayesh_patil
      MYSQL_PASSWORD: syncin_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: